# Multi-frame ASCII sprites for all 18 pet species.

SPRITES = {
    "blob": {
        "idle": ["frame1", "frame2"],
        "happy": ["happy"],
        "sad": ["sad"],
        "sleep": ["sleep"],
        "eat": ["eat"],
    },
    "duck": {
        "idle": ["frame1", "frame2"],
        "happy": ["happy"],
        "sad": ["sad"],
        "sleep": ["sleep"],
        "eat": ["eat"],
    },
    "goose": {
        "idle": ["frame1", "frame2"],
        "happy": ["happy"],
        "sad": ["sad"],
        "sleep": ["sleep"],
        "eat": ["eat"],
    },
    "cat": {
        "idle": ["frame1", "frame2"],
        "happy": ["happy"],
        "sad": ["sad"],
        "sleep": ["sleep"],
        "eat": ["eat"],
    },
    "dragon": {
        "idle": ["frame1", "frame2"],
        "happy": ["happy"],
        "sad": ["sad"],
        "sleep": ["sleep"],
        "eat": ["eat"],
    },
    "octopus": {
        "idle": ["frame1", "frame2"],
        "happy": ["happy"],
        "sad": ["sad"],
        "sleep": ["sleep"],
        "eat": ["eat"],
    },
    "owl": {
        "idle": ["frame1", "frame2"],
        "happy": ["happy"],
        "sad": ["sad"],
        "sleep": ["sleep"],
        "eat": ["eat"],
    },
    "penguin": {
        "idle": ["frame1", "frame2"],
        "happy": ["happy"],
        "sad": ["sad"],
        "sleep": ["sleep"],
        "eat": ["eat"],
    },
    "turtle": {
        "idle": ["frame1", "frame2"],
        "happy": ["happy"],
        "sad": ["sad"],
        "sleep": ["sleep"],
        "eat": ["eat"],
    },
    "snail": {
        "idle": ["frame1", "frame2"],
        "happy": ["happy"],
        "sad": ["sad"],
        "sleep": ["sleep"],
        "eat": ["eat"],
    },
    "ghost": {
        "idle": ["frame1", "frame2"],
        "happy": ["happy"],
        "sad": ["sad"],
        "sleep": ["sleep"],
        "eat": ["eat"],
    },
    "axolotl": {
        "idle": ["frame1", "frame2"],
        "happy": ["happy"],
        "sad": ["sad"],
        "sleep": ["sleep"],
        "eat": ["eat"],
    },
    "capybara": {
        "idle": ["frame1", "frame2"],
        "happy": ["happy"],
        "sad": ["sad"],
        "sleep": ["sleep"],
        "eat": ["eat"],
    },
    "cactus": {
        "idle": ["frame1", "frame2"],
        "happy": ["happy"],
        "sad": ["sad"],
        "sleep": ["sleep"],
        "eat": ["eat"],
    },
    "robot": {
        "idle": ["frame1", "frame2"],
        "happy": ["happy"],
        "sad": ["sad"],
        "sleep": ["sleep"],
        "eat": ["eat"],
    },
    "rabbit": {
        "idle": ["frame1", "frame2"],
        "happy": ["happy"],
        "sad": ["sad"],
        "sleep": ["sleep"],
        "eat": ["eat"],
    },
    "mushroom": {
        "idle": ["frame1", "frame2"],
        "happy": ["happy"],
        "sad": ["sad"],
        "sleep": ["sleep"],
        "eat": ["eat"],
    },
    "chonk": {
        "idle": ["frame1", "frame2"],
        "happy": ["happy"],
        "sad": ["sad"],
        "sleep": ["sleep"],
        "eat": ["eat"],
    },
}
